#!/bin/sh -e
# Copyright (C) 2017-2025 Ixian
# This file is part of Ixian Sandbox - www.github.com/ixian-platform/Ixian-Sandbox
#
# Ixian Sandbox is free software: you can redistribute it and/or modify
# it under the terms of the MIT License as published
# by the Open Source Initiative.
#
# Ixian Sandbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# MIT License for more details.

VERSION=0.4

BASENAME=ixian-base:24.04-$VERSION

DOCKER_CMD="docker"
DOCKER_COMPOSE_CMD="docker compose"

createBase()
{
  local baseExists=`$DOCKER_CMD images $BASENAME -q`
  if [ "$baseExists" = "" ]; then
    echo "Building Ixian Base $BASENAME"
    $DOCKER_CMD build -t $BASENAME ./ixian-base
  fi
}

create()
{
  echo "Creating Ixian containers..."
  createBase
  $DOCKER_COMPOSE_CMD -p ixian create
}

up()
{
  echo "Creating and starting Ixian containers..."
  createBase
  $DOCKER_COMPOSE_CMD -p ixian up --no-start
  start
}

down()
{
  echo "Stopping and removing Ixian containers..."
  $DOCKER_COMPOSE_CMD -p ixian down -v
}

clean()
{
  set +e
  echo "Ixian Sandbox containers will be removed."
  read -p "Are you sure you want to continue? (y/n): " confirmation
  if [ $confirmation = "y" ]; then
    $DOCKER_COMPOSE_CMD -p ixian down -v --remove-orphans --rmi all
  else
    exit 1
  fi
  set -e
}

start()
{
  echo "Starting Ixian containers..."
  # We need to start containers individually due to a bug in docker compose related to
  # replicas and port forwarding to host, otherwise we could just use:
  # docker-compose -p ixian start
  local container_ids=`$DOCKER_CMD ps -a --format 'table {{.Names}}' | grep "ixian-" | sort --version-sort`
  for item in $container_ids
  do
    $DOCKER_CMD start "$item"
  done
}

stop()
{
  echo "Stopping Ixian containers..."
  $DOCKER_COMPOSE_CMD -p ixian stop
}

build()
{
  echo "Building Ixian containers..."
  $DOCKER_COMPOSE_CMD -p ixian build --no-cache
}

execute()
{
  if [ $# -lt 2 ]; then
    echo "Exec command requires service and command parameters."
    exit 1
  fi

  local container_name=$1
  shift
  $DOCKER_COMPOSE_CMD -p ixian exec -T $container_name "$@"
}

update()
{
  local service_name=$1

  echo "Updating Ixian containers..."

  local container_ids=`$DOCKER_CMD ps --format 'table {{.Names}}' | grep "ixian-" | sort --version-sort | grep "$service_name"`
  for item in $container_ids
  do
    echo -n "Updating $item... "
    $DOCKER_CMD exec "$item" "./update.sh"

    echo -n "Restarting container "
    $DOCKER_CMD restart $item
  done
}

updateFromLocal()
{
  if [ $# -ne 2 ]; then
    echo "UpdateFromLocal command requires source path and service name."
    exit 1
  fi

  local src_path=$1
  if ! [ -d "$src_path/Ixian-Core" ]; then
    echo "Source path 'Ixian-Core' in '$src_path' does not exist."
    exit 1
  fi

  local service_name=$2

  echo "Updating Ixian containers '$service_name' from '$src_path'..."

  local container_ids=`$DOCKER_CMD ps --format 'table {{.Names}}' | grep -i "ixian-" | sort --version-sort | grep -i "$service_name"`
  local tar_cmd='tar --exclude=*/bin --exclude=*/obj --exclude=./.git --exclude=*/.vs --exclude=*/packages --exclude=*/TestClients --exclude=*/TestResults -c -O -C'
  for item in $container_ids
  do
    echo -n "Copying files to $item... "

    if echo $item | grep -iq "DLT"; then
      $tar_cmd $src_path/Ixian-Core . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-Core
      $tar_cmd $src_path/Ixian-DLT . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-DLT
      $DOCKER_CMD exec $item sh -c 'cd /opt/Ixian/Ixian-DLT/ && dos2unix rebuild.sh && /bin/sh rebuild.sh'
    fi

    if echo $item | grep -iq "S2"; then
      $tar_cmd $src_path/Ixian-Core . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-Core
      $tar_cmd $src_path/Ixian-S2 . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-S2
      $DOCKER_CMD exec $item sh -c 'cd /opt/Ixian/Ixian-S2/ && dos2unix rebuild.sh && /bin/sh rebuild.sh'
    fi

    if echo $item | grep -iq "Lite-Wallet"; then
      $tar_cmd $src_path/Ixian-Core . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-Core
      $tar_cmd $src_path/Ixian-LiteWallet . | $DOCKER_CMD cp - $item:/opt/Ixian/Ixian-LiteWallet
      $DOCKER_CMD exec $item sh -c 'cd /opt/Ixian/Ixian-LiteWallet/IxianLiteWallet/ && dos2unix rebuild.sh && /bin/sh rebuild.sh'
    fi

    if echo $item | grep -iq "Explorer"; then
      $tar_cmd $src_path/Ixian-Explorer . | $DOCKER_CMD cp - $item:/var/www/html/
    fi

    if echo $item | grep -iq "Pool"; then
      $tar_cmd $src_path/Ixian-Pool . | $DOCKER_CMD cp - $item:/var/www/html/
    fi

    echo -n "Restarting container "
    $DOCKER_CMD restart $item
  done
}

help()
{
  echo -e "Usage: ./sandbox [COMMAND] [PARAMETERS]"
  echo
  echo -e "Build and manage Ixian services in Docker."
  echo
  echo -e "\x1B[1mIxian Sandbox Help:"
  echo -e "  \x1B[1mup\t\t\t\x1B[0m- creates and starts the sandbox environment."
  echo -e "  \x1B[1mcreate\t\t\x1B[0m- creates the sandbox environment."
  echo -e "  \x1B[1mstart\t\t\t\x1B[0m- starts the sandbox environment."
  echo -e "  \x1B[1mstop\t\t\t\x1B[0m- stops the sandbox environment."
  echo -e "  \x1B[1mdown\t\t\t\x1B[0m- stops and destroys the sandbox environment."
  echo -e "  \x1B[1mbuild\t\t\t\x1B[0m- rebuilds the sandbox environment."
  echo -e "  \x1B[1mclean\t\t\t\x1B[0m- removes the container and deletes temporary files."
  echo -e "  \x1B[1mexec\t\t\t\x1B[0m- executes a shell command for the specified service."
  echo -e "  \x1B[1mupdate\t\t\x1B[0m- triggers update command for each service."
  echo -e "  \x1B[1mupdateFromLocal\t\x1B[0m- updates and rebuilds services from local storage."
  echo
  echo -e "For more information about Ixian Platform visit https://www.ixian.io/"
}

sandbox()
{
  local sandbox_cmd=$1
  if [ $1 ]; then
    shift
  fi

  case $sandbox_cmd in
    up)
      up
      ;;
			
    down)
      down
      ;;
      
    create)
      create
      ;;

    start)
      start
      ;;

    stop)
      stop
      ;;
	  
    exec)
      execute "$@"
      ;;

    build)
      build
      ;;
	  
    clean)
      clean
      ;;

    update)
      update "$@"
      ;;

    updateFromLocal)
      updateFromLocal "$@"
      ;;

    version)
      echo Ixian Sandbox version $VERSION
      ;;

    help)
      help
      ;;

    *)
      if [ $sandbox_cmd ]; then
        echo -e "\x1B[41mError\x1B[0m: Unknown command '$sandbox_cmd'"
        echo
      fi

      help
      ;;
  esac
}

if ! [ -x "$(command -v $DOCKER_COMPOSE_CMD)" ]; then
  echo -e "\x1B[41mError\x1B[0m: $DOCKER_COMPOSE_CMD is not installed." >&2
  exit 1
fi

sandbox "$@"
