services:
  ixian-s2:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        URL: "https://github.com/ixian-platform"
        #BRANCH: "master"
        #SHA: ""
    environment:
      S2_PORT: "10236"
      NETWORK_TYPE: "MAINNET"
      #SEED_NODE: "ixian-dlt-1:10234"
      #BOOTSTRAP_URL: ""
      #GENESIS_FILE: ""
      #WALLET_FILE: ""
      #WALLET_PASSWORD: ""
    ports:
      - "8083:8081"
      - "10236:10236"
    expose:
      - "8081"
      - "10236"