services:
  ixian-dlt:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        URL: "https://github.com/ixian-platform"
        #BRANCH: "master"
        #SHA: ""
    environment:
      DLT_PORT: "10234"
      NETWORK_TYPE: "MAINNET"
      #GENESIS_FUNDS: "100000000000"
      #SEED_NODE: "ixian-dlt-1:10234"
      #BOOTSTRAP_URL: ""
      #GENESIS_FILE: ""
      #WALLET_FILE: ""
      #WALLET_PASSWORD: ""
    ports:
      - "8081:8081"
      - "10234:10234"
    expose:
      - "8081"
      - "10234"
