services:
  ixian-explorer:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        URL: "https://github.com/ixian-platform"
        BRANCH: "main"
        #SHA: ""
        DLT_URL: "http://ixian-dlt:8081"
    ports:
      - "443:443"
    expose:
      - "443"
      