services:
  ixian-pool:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        URL: "https://github.com/ixian-platform"
        BRANCH: "master"
        #SHA: ""
        POOL_REWARD_ADDRESS: "153xXfVi1sznPcRqJur8tutgrZecNVYGSzetp47bQvRfNuDix"
        POOL_FEE: "0.02"
        POOL_URL: "https://ixian-pool/"
        POOL_NAME: "My Ixian Pool"
        DLT_URL: "http://ixian-dlt:8081"
    ports:
      - "443:443"
    expose:
      - "443"
      